name: Release
on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: [completed]
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' && github.repository_owner == 'jschaf' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Create release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
